const actionsConstants = {
    LOG_IN: 'LOG_IN',
    SET_REVIEWS: 'SET_REVIEWS',
    SET_PROFILE_DATA: 'SET_PROFILE_DATA',
    SET_BALANCE: 'SET_BALANCE',
    SET_AVATAR: 'SET_AVATAR',
    DELETE_AVATAR: 'DELETE_AVATAR',
    SET_GOAL: 'SET_GOAL',
    EDIT_GOAL: 'EDIT_GOAL',
    SET_TRANSACTIONS: 'SET_TRANSACTIONS'
}

export default actionsConstants;